#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx, setting it to listen on port 80, and serving
# a page that returns a "Hello World" string.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Create custom 404.html file
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html

# Using sed to add Nginx configuration for 301 redirect
sudo sed -i '/server_name/ a location \/redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; } error_page 404 /error_404.html;location = /error_404.html { root /var/www/html; internal; }' /etc/nginx/sites-available/default

# Restarting Nginx
sudo service nginx restart

echo -e "\nNginx configuration updated with a 301 redirect.\n"
