#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.new

nice -n 10 sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new 
sudo cp -f ~/hosts.new /etc/hosts 
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
