#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.bak

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
